spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/html/
  application:
    name: tour-portal
  redis:
    host: localhost
    port: 6379
    timeout: 0
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0

server:
  port: 8081
  connection-timeout: 10000000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  httpclient:
    connection-timeout: 10000000
ribbon:
  ReadTimeout: 120000   #连接之后，读取超时（可以打断点测试）
  ConnectTimeout: 30000  #建立连接超时时间


com:
  xmy:
    properties:
      indexUrl: http://localhost:8081/
      picUrl: http://localhost:8081/